fint:
  resource-gateway:
    resources:
      entity:
        enabled: true
        refresh:
          interval-ms: 518400000
          topic-retention-time-offset-ms: 86400000
        pull:
          initial-delay-ms: 5000
          fixed-delay-ms: 900000
        entity-pipelines:
          - resource-reference: arkiv.noark.administrativenhet
          - resource-reference: arkiv.noark.klassifikasjonssystem
          - resource-reference: arkiv.kodeverk.rolle
          - resource-reference: arkiv.kodeverk.saksstatus
          - resource-reference: arkiv.noark.arkivdel
          - resource-reference: arkiv.kodeverk.skjermingshjemmel
          - resource-reference: arkiv.kodeverk.tilgangsrestriksjon
          - resource-reference: arkiv.kodeverk.klassifikasjonstype
          - resource-reference: arkiv.kodeverk.dokumentstatus
          - resource-reference: arkiv.kodeverk.dokumenttype
          - resource-reference: arkiv.kodeverk.journalstatus
          - resource-reference: arkiv.kodeverk.variantformat
          - resource-reference: arkiv.noark.arkivressurs
          - resource-reference: administrasjon.personal.personalressurs
            self-link-key-filter: ansattnummer
          - resource-reference: administrasjon.personal.person
            self-link-key-filter: fodselsnummer
      request:
        enabled: true
        request-pipelines:
          - resource-reference: arkiv.noark.sak
            fint-endpoint-format: "/arkiv/noark/sak/mappeid/%s"
            requestParameterNames: "mappe-id"
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: flyt
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}